### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by nlangford** [tetsujin1979/ngSkySports#1]
Hi Tetsujin, I was just wondering if you could figure out how to return the form for a fixture?

For example: http://www.skysports.com/football/arsenal-vs-basel/form/366869

**Comment by tetsujin1979** [comment]
Sure, the form endpoint is at http://a.365dm.com/api/score-centre/v1/football/fixture/information/{fixtureId}
so http://a.365dm.com/api/score-centre/v1/football/fixture/information/366869

**Comment by nlangford** [comment]
Thanks tetsujin. Is there any other end points other than the ones on ngSkySports and the form?

Thanks

**Comment by nlangford** [comment]
Hi, I have one other endpoint that I wonder if you have access to

http://www.skysports.com/football/bolton-vs-blackpool/stats/367327

I have tried looking into Squid and getting these myself but I'm not sure what to do with it.

**Comment by tetsujin1979** [comment]
it's at http://d.365dm.com/api/score-centre/v1/football/fixture/statistics/367327
Best advice I can give you is open http://sc.365dm.com/ and monitor the network tab in developer tools (Chrome) or Firebug (Firefox)

**Comment by nlangford** [comment]
Thanks tetsujin1979
